// Code generated by fizzbee-mbt generator; DO NOT EDIT.

import { runTests, ActionFunc } from '@fizzbee/mbt';
import { ControllerRole, ControllerModel } from './controller_interfaces.js';
import { newControllerModel, getTestOptions } from './controller_adapters.js';

// Registry keyed by role type ("" means top-level model actions)
const actionRegistry = new Map<string, Map<string, ActionFunc>>([
  ['', new Map<string, ActionFunc>([
  ])],
  ['Controller', new Map<string, ActionFunc>([
    ['Status', async (inst: any, args: any[]) => {
      return (inst as ControllerRole).actionStatus(args);
    }],
  ])],
]);

async function testController(): Promise<void> {
  const model = newControllerModel();
  const options = getTestOptions();

  try {
    await runTests(model, actionRegistry, options);
    model.cleanupAll();
  } catch (error) {
    console.error('Test failed:', error);
    process.exit(1);
  }
}

// Run tests
testController();