// Code generated by fizzbee-mbt generator; DO NOT EDIT.
// Source: ../controller.fizz

import { Role, Model, Arg } from '@fizzbee/mbt';

// Role interfaces

export interface ControllerRole extends Role {
  actionStatus(args: Arg[]): Promise<any>;
}

// Model interface for the whole specification
export interface ControllerModel extends Model {
  // Inherits from Model: init(), cleanup(), getRoles()
}