// Code generated by fizzbee-mbt generator; DO NOT EDIT.
// Source: conformance.fizz

import { Role, Model, Arg } from '@fizzbee/mbt';

// Role interfaces

export interface ControllerRole extends Role {
  actionStart(args: Arg[]): Promise<any>;
  actionReview(args: Arg[]): Promise<any>;
  actionProof(args: Arg[]): Promise<any>;
  actionCorrupt(args: Arg[]): Promise<any>;
  actionRestart(args: Arg[]): Promise<any>;
  actionInspect(args: Arg[]): Promise<any>;
  actionResume(args: Arg[]): Promise<any>;
  actionOverlap(args: Arg[]): Promise<any>;
}

// Model interface for the whole specification
export interface ConformanceModel extends Model {
  // Inherits from Model: init(), cleanup(), getRoles()
}