// Code generated by fizzbee-mbt generator; DO NOT EDIT.

import { runTests, ActionFunc } from '@fizzbee/mbt';
import { ControllerRole, ConformanceModel } from './conformance_interfaces.js';
import { newConformanceModel, getTestOptions } from './conformance_adapters.js';

// Registry keyed by role type ("" means top-level model actions)
const actionRegistry = new Map<string, Map<string, ActionFunc>>([
  ['', new Map<string, ActionFunc>([
  ])],
  ['Controller', new Map<string, ActionFunc>([
    ['Start', async (inst: any, args: any[]) => {
      return (inst as ControllerRole).actionStart(args);
    }],
    ['Review', async (inst: any, args: any[]) => {
      return (inst as ControllerRole).actionReview(args);
    }],
    ['Proof', async (inst: any, args: any[]) => {
      return (inst as ControllerRole).actionProof(args);
    }],
    ['Corrupt', async (inst: any, args: any[]) => {
      return (inst as ControllerRole).actionCorrupt(args);
    }],
    ['Restart', async (inst: any, args: any[]) => {
      return (inst as ControllerRole).actionRestart(args);
    }],
    ['Inspect', async (inst: any, args: any[]) => {
      return (inst as ControllerRole).actionInspect(args);
    }],
    ['Resume', async (inst: any, args: any[]) => {
      return (inst as ControllerRole).actionResume(args);
    }],
    ['Overlap', async (inst: any, args: any[]) => {
      return (inst as ControllerRole).actionOverlap(args);
    }],
  ])],
]);

async function testConformance(): Promise<void> {
  const model = newConformanceModel();
  const options = getTestOptions();

  try {
    await runTests(model, actionRegistry, options);
    model.cleanupAll();
  } catch (error) {
    console.error('Test failed:', error);
    process.exit(1);
  }
}

// Run tests
testConformance();